### ISSUE TITLE
App crashes because it Failed to allocate memory to read the file

### ISSUE THREAD

**Issue by masterT** [prscX/react-native-file-type#1]

**Comment by prscX** [comment]
Thanks @masterT for raising the issue and PR.

I have pushed the release with [V0.0.5](https://github.com/prscX/react-native-file-type/releases/tag/v0.0.5). Can you please install and verify the same.

Please let me know incase you face any issues.

Thanks
</ Pranav >

**Comment by masterT** [comment]
Awesome!
